### ISSUE TITLE
Error loading source maps

### ISSUE THREAD

**Issue by prodrammer** [patomation/omit-deep#1]
First off, thanks for your module. It is very helpful.

I'm getting an error inside of a React app when including this package. The error does not stop my application from running, but it does clutter the log output.

```
Failed to parse source map from '/Users/<redacted>/node_modules/@patomation/omit-deep/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/<redacted>/node_modules/@patomation/omit-deep/src/index.ts'
```

I think the error would be resolved if you put your source code inside the "src" folder in the npm package.

Let me know what you think. I can also make a PR for this if you'd like.

Thanks!

**Comment by patomation** [comment]
@prodrammer  published 1.0.2 with your bug fix. Let me know if you still are using this package. Now the `/node_modules/@patomation/omit-deep/src/index.ts` should exist. 

Thanks again
